### ISSUE TITLE
java.lang.ClassNotFoundException: javax.xml.bind.JAXBException

### ISSUE THREAD

**Issue by m1rc0** [iNPUTmice/ComplianceTester#156]
When running, the following exception occurs. macOS 10.13.3 and java version "9.0.1".

```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at eu.siacs.compliance.TestSuiteFactory.create(TestSuiteFactory.java:13)
	at eu.siacs.ComplianceTester.runTestSuite(ComplianceTester.java:69)
	at eu.siacs.ComplianceTester.runTestSuite(ComplianceTester.java:63)
	at eu.siacs.ComplianceTester.main(ComplianceTester.java:57)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 4 more
```

**Comment by tomas-chrastina** [comment]
As mentioned in:

**Comment by tomas-chrastina** [comment]
Try search ;). Already mentioned:

**Comment by tomas-chrastina** [comment]
Try to run with
`java --add-modules=java.xml.bind,java.activation -jar target/ComplianceTester-0.2.3.jar username@domain password`

as mentioned in #143 (Better support for Java 9?).
