### ISSUE TITLE
exception rocks.xmpp.core.stanza.StanzaException

### ISSUE THREAD

**Issue by hannob** [iNPUTmice/ComplianceTester#59]
When testing the xmpp server from chat.hipchat.com I get an exception several times.
I think that's not intended.

Hipchat has a free account signup, so you should be able to test this (but I have a test account you could use for testing also, mail me if needed).

```
rocks.xmpp.core.stanza.StanzaException: feature-not-implemented  -  (type 'cancel': do not retry (the error cannot be remedied))
	at rocks.xmpp.core.session.XmppSession.lambda$sendAndAwait$9(XmppSession.java:724)
	at rocks.xmpp.util.XmppUtils.lambda$notifyEventListeners$3(XmppUtils.java:192)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:404)
	at rocks.xmpp.util.XmppUtils.notifyEventListeners(XmppUtils.java:190)
	at rocks.xmpp.core.session.XmppSession.lambda$handleElement$16(XmppSession.java:1012)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by iNPUTmice** [comment]
If anything that's just too much logging. feature-not-implemented is a server side error message that just means that service discovery (an existential feature) is not supported on Hipchat. IIRC those error messages are going to stderr though and shouldn't influence the actual testing output.
