### ISSUE TITLE
Runtime failure (Could not generate DH keypair) 

### ISSUE THREAD

**Issue by nidico** [iNPUTmice/ComplianceTester#9]
Trying to run the suite with OpenJDK 1.8.0_91 fails with the following stacktrace:

```
Use compliance suite 'Advanced Server Core Compliance Suite' to test jabber.fsfe.org

rocks.xmpp.core.XmppException: javax.xml.stream.XMLStreamException: javax.net.ssl.SSLException: java.lang.RuntimeException: Could not generate DH keypair
        at rocks.xmpp.core.session.XmppSession.throwAsXmppExceptionIfNotNull(XmppSession.java:255)
        at rocks.xmpp.core.session.XmppClient.connect(XmppClient.java:251)
        at rocks.xmpp.core.session.XmppSession.connect(XmppSession.java:301)
        at eu.siacs.compliance.suites.AbstractTestSuite.run(AbstractTestSuite.java:31)
        at eu.siacs.ComplianceTester.runTestSuite(ComplianceTester.java:63)
        at eu.siacs.ComplianceTester.main(ComplianceTester.java:53)
Caused by: javax.xml.stream.XMLStreamException: javax.net.ssl.SSLException: java.lang.RuntimeException: Could not generate DH keypair
        at com.sun.xml.internal.stream.writers.XMLStreamWriterImpl.flush(XMLStreamWriterImpl.java:399)
        at rocks.xmpp.core.session.XmppStreamWriter.lambda$openStream$3(XmppStreamWriter.java:181)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
        Suppressed: javax.xml.stream.XMLStreamException: javax.net.ssl.SSLException: Connection has been shutdown: javax.net.ssl.SSLException: java.lang.RuntimeException: Could not generate DH keypair
                at com.sun.xml.internal.stream.writers.XMLStreamWriterImpl.close(XMLStreamWriterImpl.java:378)
                at rocks.xmpp.util.PrefixFreeCanonicalizationWriter.close(PrefixFreeCanonicalizationWriter.java:148)
                at rocks.xmpp.core.session.XmppStreamWriter.notifyException(XmppStreamWriter.java:227)
                at rocks.xmpp.core.session.XmppStreamWriter.lambda$openStream$3(XmppStreamWriter.java:188)
                ... 7 more
        Caused by: javax.net.ssl.SSLException: Connection has been shutdown: javax.net.ssl.SSLException: java.lang.RuntimeException: Could not generate DH keypair
                at sun.security.ssl.SSLSocketImpl.checkEOF(SSLSocketImpl.java:1541)
                at sun.security.ssl.SSLSocketImpl.checkWrite(SSLSocketImpl.java:1553)
                at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:71)
                at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
                at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
                at com.sun.xml.internal.stream.writers.UTF8OutputStreamWriter.flush(UTF8OutputStreamWriter.java:138)
                at com.sun.xml.internal.stream.writers.XMLStreamWriterImpl.close(XMLStreamWriterImpl.java:376)
                ... 10 more
        Caused by: javax.net.ssl.SSLException: java.lang.RuntimeException: Could not generate DH keypair
                at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
                at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
                at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1906)
                at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1889)
                at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1815)
                at sun.security.ssl.AppInputStream.read(AppInputStream.java:116)
                at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
                at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
                at com.sun.org.apache.xerces.internal.impl.XMLEntityManager$RewindableInputStream.read(XMLEntityManager.java:2899)
                at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:709)
                at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startEntity(XMLEntityManager.java:1305)
                at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startDocumentEntity(XMLEntityManager.java:1256)
                at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.setInputSource(XMLDocumentScannerImpl.java:257)
                at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.setInputSource(XMLStreamReaderImpl.java:199)
                at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.<init>(XMLStreamReaderImpl.java:184)
                at com.sun.xml.internal.stream.XMLInputFactoryImpl.getXMLStreamReaderImpl(XMLInputFactoryImpl.java:277)
                at com.sun.xml.internal.stream.XMLInputFactoryImpl.createXMLStreamReader(XMLInputFactoryImpl.java:155)
                at com.sun.xml.internal.stream.XMLInputFactoryImpl.createXMLEventReader(XMLInputFactoryImpl.java:102)
                at rocks.xmpp.core.session.XmppStreamReader.lambda$startReading$71(XmppStreamReader.java:110)
                ... 3 more
        Caused by: java.lang.RuntimeException: Could not generate DH keypair
                at sun.security.ssl.DHCrypt.<init>(DHCrypt.java:142)
                at sun.security.ssl.DHCrypt.<init>(DHCrypt.java:114)
                at sun.security.ssl.ClientHandshaker.serverKeyExchange(ClientHandshaker.java:708)
                at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:268)
                at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
                at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
                at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
                at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
                at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:928)
                at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
                ... 16 more
        Caused by: java.security.InvalidAlgorithmParameterException: Prime size must be multiple of 64, and can only range from 512 to 2048 (inclusive)
                at com.sun.crypto.provider.DHKeyPairGenerator.initialize(DHKeyPairGenerator.java:120)
                at java.security.KeyPairGenerator$Delegate.initialize(KeyPairGenerator.java:674)
                at sun.security.ssl.DHCrypt.<init>(DHCrypt.java:128)
                ... 25 more
        [CIRCULAR REFERENCE:javax.net.ssl.SSLException: java.lang.RuntimeException: Could not generate DH keypair]
```

**Comment by iNPUTmice** [comment]
jabber.fsfe.org works fine for me. (OpenJDK 8 u92 from Arch)
A quick google search seems to indicate this could be problem in your runtime.
I don't know if there is a way to work around in the library. But in this case the ComplicaneTester is not the right place to do this. You could report it to babbler (the XMPP library we use.)

**Comment by iNPUTmice** [comment]
https://xmpp.net/result.php?domain=jabber.fsfe.org&type=client#ciphers tells me that the server is using DH bitsizes of 8192 which your runtime can not handle.
> ```Caused by: java.security.InvalidAlgorithmParameterException: Prime size must be multiple of 64, and can only range from 512 to 2048 (inclusive)```

is this the default value of prosody or did the admin go crazy here? 8k seems very high to me.

**Comment by iNPUTmice** [comment]
> jabber.fsfe.org works fine for me. (OpenJDK 8 u92 from Arch)

correction it doesn't. My OpenJDK has the same DH boundaries. That's something that will get fixed in JDK 9.

**Comment by alex1702** [comment]
At oracles java 9 i have this error:

> `Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
> 	at eu.siacs.compliance.TestSuiteFactory.create(TestSuiteFactory.java:13)
> 	at eu.siacs.ComplianceTester.runTestSuite(ComplianceTester.java:61)
> 	at eu.siacs.ComplianceTester.main(ComplianceTester.java:53)
> Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
> 	at jdk.internal.loader.BuiltinClassLoader.loadClass(java.base@9-ea/BuiltinClassLoader.java:366)
> 	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(java.base@9-ea/ClassLoaders.java:185)
> 	at java.lang.ClassLoader.loadClass(java.base@9-ea/ClassLoader.java:419)
> 	... 3 more`

**Comment by alex1702** [comment]
ok i have the solution. The dhparam can not be bigger then 2048bit at Java 8.
