### ISSUE TITLE
Key size not supported

### ISSUE THREAD

**Issue by ro0kie4** [iNPUTmice/ComplianceTester#97]
```
Use compliance suite 'Advanced Server Mobile Compliance Suite' to test datentopf.org

rocks.xmpp.core.XmppException: javax.xml.stream.XMLStreamException: javax.net.ssl.SSLException: java.lang.RuntimeException: Could not generate DH keypair
	at rocks.xmpp.core.session.XmppSession.throwAsXmppExceptionIfNotNull(XmppSession.java:255)
	at rocks.xmpp.core.session.XmppClient.connect(XmppClient.java:251)
	at rocks.xmpp.core.session.XmppSession.connect(XmppSession.java:301)
	at eu.siacs.compliance.suites.AbstractTestSuite.run(AbstractTestSuite.java:31)
	at eu.siacs.ComplianceTester.runTestSuite(ComplianceTester.java:69)
	at eu.siacs.ComplianceTester.runTestSuite(ComplianceTester.java:61)
	at eu.siacs.ComplianceTester.main(ComplianceTester.java:55)
Caused by: javax.xml.stream.XMLStreamException: javax.net.ssl.SSLException: java.lang.RuntimeException: Could not generate DH keypair
	at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.setInputSource(XMLStreamReaderImpl.java:212)
	at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.<init>(XMLStreamReaderImpl.java:184)
	at com.sun.xml.internal.stream.XMLInputFactoryImpl.getXMLStreamReaderImpl(XMLInputFactoryImpl.java:277)
	at com.sun.xml.internal.stream.XMLInputFactoryImpl.createXMLStreamReader(XMLInputFactoryImpl.java:155)
	at com.sun.xml.internal.stream.XMLInputFactoryImpl.createXMLEventReader(XMLInputFactoryImpl.java:102)
	at rocks.xmpp.core.session.XmppStreamReader.lambda$startReading$71(XmppStreamReader.java:110)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLException: java.lang.RuntimeException: Could not generate DH keypair
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1906)
	at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1889)
	at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1815)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:116)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager$RewindableInputStream.read(XMLEntityManager.java:2890)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:709)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startEntity(XMLEntityManager.java:1304)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startDocumentEntity(XMLEntityManager.java:1255)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.setInputSource(XMLDocumentScannerImpl.java:253)
	at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.setInputSource(XMLStreamReaderImpl.java:199)
	... 8 more
Caused by: java.lang.RuntimeException: Could not generate DH keypair
	at sun.security.ssl.DHCrypt.<init>(DHCrypt.java:142)
	at sun.security.ssl.DHCrypt.<init>(DHCrypt.java:114)
	at sun.security.ssl.ClientHandshaker.serverKeyExchange(ClientHandshaker.java:711)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:268)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:961)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:928)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	... 16 more
Caused by: java.security.InvalidAlgorithmParameterException: DH key size must be multiple of 64, and can only range from 512 to 2048 (inclusive). The specific key size 4096 is not supported
	at com.sun.crypto.provider.DHKeyPairGenerator.initialize(DHKeyPairGenerator.java:128)
	at java.security.KeyPairGenerator$Delegate.initialize(KeyPairGenerator.java:674)
	at sun.security.ssl.DHCrypt.<init>(DHCrypt.java:128)
	... 25 more
```

**DH key size must be multiple of 64, and can only range from 512 to 2048 (inclusive). The specific key size 4096 is not supported**

**Comment by iNPUTmice** [comment]
This is a Java limitation. There is nothing we can do about that.

**Comment by ro0kie4** [comment]
Oh alright.
Thanks for the reply 

Am 12. April 2017 17:32:58 MESZ schrieb Daniel Gultsch <notifications@github.com>:
>This is a Java limitation. There is nothing we can do about that.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/iNPUTmice/ComplianceTester/issues/97#issuecomment-293616721

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
